site_name: Reproducible and Scalable Research with Snakemake and Software Containers
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1 - Containers:
      - Introduction to containers: course_material/day1/introduction_containers.md
      - Managing containers and images: course_material/day1/managing_docker.md
      - Working with dockerfiles: course_material/day1/dockerfiles.md
      - Running containers with apptainer: course_material/day1/apptainer.md
    - Day 2 - Snakemake:
      - General guidelines: course_material/day2/1_guidelines.md
      - Introduction to Snakemake: course_material/day2/2_introduction_snakemake.md
      - Making a more general-purpose Snakemake workflow: course_material/day2/3_generalising_snakemake.md
      - Decorating and optimising a Snakemake workflow: course_material/day2/4_optimising_snakemake.md
      - Being reproducible with Snakemake: course_material/day2/5_reproducibility_snakemake.md
      - Running Snakemake in an HPC environment: course_material/day2/7_hpc_snakemake.md
      - Additional concepts and workflow design/debugging: course_material/day2/6_debugging_snakemake.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.code.copy

extra:
  version:
    provider: mike
  analytics:
    provider: matomo
    base_url: https://matomo.sib.swiss/
    site_id: 220

copyright: >
  Copyright &copy; 2021-2024 SIB Swiss institute of Bioinformatics -
  <a href="#__consent">Change cookie settings</a>

# Repository
repo_name: sib-swiss/containers-snakemake-training
repo_url: https://github.com/sib-swiss/containers-snakemake-training
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
